# Generated by Django 3.1.1 on 2020-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='club',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='concepts',
            field=models.ManyToManyField(to='concepts.Concept'),
        ),
        migrations.AddField(
            model_name='club',
            name='contacts',
            field=models.ManyToManyField(to='concepts.Contact'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(default='Hygienekonzept', max_length=50),
        ),
    ]
