# Generated by Django 3.1.1 on 2020-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hygienekonzept', max_length=50)),
                ('pdf', models.FileField(upload_to='concepts/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access_count', models.IntegerField(default=0)),
                ('concepts', models.ManyToManyField(to='concepts.Concept')),
                ('contacts', models.ManyToManyField(to='concepts.Contact')),
            ],
            options={
                'ordering': ['-access_count'],
            },
        ),
    ]
